Adding network table doc
filecoin-project/tpm pull request #80
Opened 2021-12-09 18:04 UTC by SgtCoin

2021-12-09 18:34 UTC, SgtCoin commented
I changed the name to README.md so it will render correctly and added the missing fips into the v13 and v14 sections.

2021-12-09 18:47 UTC, arajasek requested changes
Thanks for the PR! Just a couple nits.

2021-12-09 18:47 UTC, arajasek commented on Network Upgrades/README.md
> +| network upgrade # | upgrade name | actors version |                     FIPs included                    |  Epoch  |
```suggestion
| Upgrade # | Upgrade name | Actors Version |                     FIPs included                    |  Epoch  |

```

2021-12-09 18:47 UTC, arajasek commented on Network Upgrades/README.md
> +|        v12        |     Turbo    |     v4.0.0     |                        No FIPs                       |  712.20 |
epoch seems wrong?

2021-12-09 18:47 UTC, arajasek commented on Network Upgrades/README.md
> +|        v13        |  HyperDrive  |     v5.0.0     | FIP-0008 / FIP-0011 / FIP-0012 / FIP-0013 / FIP-0015 |  892800 |
Nit: Maybe separate the FIPs by commas?

2021-12-09 18:48 UTC, SgtCoin commented on Network Upgrades/README.md
> +|        v12        |     Turbo    |     v4.0.0     |                        No FIPs                       |  712.20 |
I see it... typo.. fixing

2021-12-09 18:48 UTC, SgtCoin commented on Network Upgrades/README.md
> +|        v13        |  HyperDrive  |     v5.0.0     | FIP-0008 / FIP-0011 / FIP-0012 / FIP-0013 / FIP-0015 |  892800 |
will do

2021-12-09 18:55 UTC, SgtCoin reviewed
Fixed all the things.

2021-12-09 19:11 UTC, arajasek approved these changes
Looks good to me!

It would be nice to add links to the FIPs and actors tags (see [here](https://github.com/filecoin-project/tpm/blob/master/Network%20Upgrades/v11.md) for an example), but it's not necessary.

2021-12-09 20:25 UTC, arajasek approved these changes
2 last nits

2021-12-09 20:25 UTC, arajasek commented on Network Upgrades/README.md
> +|        v11        |   Norwegian  |     v3.1.0     |                       [FIP-00014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md)                      |  665280 |
```suggestion
|        v11        |   Norwegian  |     v3.1.0     |                       [FIP-0014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md)                      |  665280 |

```

2021-12-09 20:25 UTC, arajasek commented on Network Upgrades/README.md
> +| Upgrade #         | Upgrade name | Actors Version |                     FIPs included                    |  Epoch  |
Can we add a 

## Network Upgrades to the start of this file

2021-12-09 20:32 UTC, SgtCoin commented on Network Upgrades/README.md
> +|        v11        |   Norwegian  |     v3.1.0     |                       [FIP-00014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md)                      |  665280 |
Fixed

2021-12-09 20:32 UTC, SgtCoin commented on Network Upgrades/README.md
> +| Upgrade #         | Upgrade name | Actors Version |                     FIPs included                    |  Epoch  |
Added

2021-12-15 19:03 UTC, kaitlin-beegle commented
This is a great tool! Thanks for organizing this, @SgtCoin! 

@arajasek I wonder if it's worth adding an explainer, re: FIPs 2, 6, and 7? I assume these were implemented as need-to-have protocol enhancements outside of a standard upgrade, but it might be nice to add clarifying details as to why.

2021-12-15 23:21 UTC, arajasek commented
@kaitlin-beegle Taking them one-by-one:

- FIP-0002 was adopted in network version which was before mainnet -- the NV docs I added in #78 only cover the mainnet-and-after versions. I could add those docs too, though, if you'd like.
- FIP-0006 was deferred, it never went live.
- FIP-0007 went live in nv10, I totally missed that in my PR. Gonna add it there, and @SgtCoin can you please add it here too?

2022-01-04 15:40 UTC, merged